### ISSUE TITLE
Cannot connect to Remote jupyter server on MacOS 13 Ventura.

### ISSUE THREAD

**Issue by ameyb22** [microsoft/vscode-jupyter#10969]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Well, I was using the remote connection of jupyter every day before upgrading to the beta version of macOS 13. But now I can't use the remote servers it is just stuck on the link I'm providing it's not even giving me any error stating something bad is happening
<img width="690" alt="Screenshot 2022-07-29 at 12 32 27 AM" src="https://user-images.githubusercontent.com/82094447/181617145-a7379b06-a45b-4965-bdd8-59759c6c1ee2.png">
.

### VS Code Version

1.69.2

### Jupyter Extension Version

v2022.6.1201981810

### Jupyter logs

```shell
error 0:33:48.706: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/meow/.vscode/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/node_modules/@jupyterlab/services.js:2:156575)
	at m.dispose (/Users/meow/.vscode/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/node_modules/@jupyterlab/services.js:2:48238)
	at u.dispose (/Users/meow/.vscode/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:24:141980)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
info 0:34:3.973: Creating server with url : https://ni3k16prd3.clg07azjl.paperspacegradient.com/
error 0:34:7.203: Failed to select Jupyter Uri, Class name = C, completed in 20031ms, has a falsy return value, Arg 1: true, Arg 2: "nativeNotebookStatusBar", Return Value: undefined [Error: Password is required.,    at checkRequired (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/keytar/lib/keytar.js:5:11),    at Object.setPassword (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/keytar/lib/keytar.js:20:5),    at u (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:33:8527),    at async f.setPassword (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:33:8948)]
```

### Coding Language and Runtime Version

Python v3.9.13

### Language Extension Version (if applicable)

v2022.7.40

### Anaconda Version (if applicable)

miniforge 4.13.0

### Running Jupyter locally or remotely?

Remote

**Comment by amunger** [comment]
It looks like the server requires a password, but for some reason we're failing to bring up the prompt for it

**Comment by ameyb22** [comment]
> It looks like the server requires a password, but for some reason we're failing to bring up the prompt for it

No, it is working fine on **vscode.dev with jupyter extension** and **vs code in windows virtual machine**, but it's only causing an issue in macOS 13 beta. rest of the things work as expected only jupyter remote server isn't working. could it be due to the pre-released os?

**Comment by amunger** [comment]
> could it be due to the pre-released os?

Could be caused by that. I can check if any Mac users on our team have access to get that OS to try and troubleshoot this. But we might still just be able to dig into the code from that stackframe and figure it out from there.

**Comment by ameyb22** [comment]
> Could be caused by that. I can check if any Mac users on our team have access to get that OS to try and troubleshoot this. But we might still just be able to dig into the code from that stackframe and figure it out from there.

looking forward to your comment. Thank you.

**Comment by DonJayamanne** [comment]
@ameyb22 do you happen to have some of the Azure ML extensions installed?
If you do, please could you disable all of the other non-essential extensions such as the Azure related extensions.
Also, please could you update to the latest version of the Jupyter extesnion (2022.7.xx), as we've fixed a few auth related issues in there.

Let me know how this goes.

**Comment by ameyb22** [comment]
I disabled Azure Extensions and upgraded the Jupyter Extension and everything working as expected, thanks a lot! should I close the issue? @DonJayamanne

**Comment by DonJayamanne** [comment]
> , thanks a lot! 

thanks for the confirmation.

> should I close the issue

let's leave this issue open. i think we'll need to fix this as others could be running into this today.

**Comment by IanMatthewHuff** [comment]
Should be the same as #10300 I believe, but let's keep this open to make sure. I'm looking into it today.

**Comment by IanMatthewHuff** [comment]
> I disabled Azure Extensions and upgraded the Jupyter Extension and everything working as expected, thanks a lot! should I close the issue? @DonJayamanne

@ameyb22 Quick question on this (if you don't mind). To fix this you took two steps, 1. updating Jupyter extension and 2. Disabling AML extension. Is the issue still fixed if you update the Jupyter extension but you do have the AML extension installed? Just trying to narrow down what fixed this for you. I'm investigating now and I am cleaning up one password issue with remote scenarios (#10300) but I'm not reproing this scenario that you have, and I don't believe that my fix for that issue would clean up the callstack that I see in your issue.

**Comment by ameyb22** [comment]
@IanMatthewHuff when I opened this issue I was on macOS 13 beta and I couldn't even use the local jupyter server with the link. Well, I downgraded my back to a public stable version last week since then everything is working as it should be. I think there was an issue with os only because most of the things weren't working accordingly. coming on your current question, I'm not sure what helped me with the issue I was facing: updating the jupyter extension or downgrading the system. But I did try with AML extension enabled as well as disabled everything worked fine. please tell me if you need more clarification.

**Comment by ameyb22** [comment]
> > I disabled Azure Extensions and upgraded the Jupyter Extension and everything working as expected, thanks a lot! should I close the issue? @DonJayamanne
> 
> @ameyb22 Quick question on this (if you don't mind). To fix this you took two steps, 1. updating Jupyter extension and 2. Disabling AML extension. Is the issue still fixed if you update the Jupyter extension but you do have the AML extension installed? Just trying to narrow down what fixed this for you. I'm investigating now and I am cleaning up one password issue with remote scenarios (#10300) but I'm not reproing this scenario that you have, and I don't believe that my fix for that issue would clean up the callstack that I see in your issue.

when I opened this issue I was on macOS 13 beta and I couldn't even use the local jupyter server with the link. Well, I downgraded my back to a public stable version last week since then everything is working as it should be. I think there was an issue with os only because most of the things weren't working accordingly. coming on your current question, I'm not sure what helped me with the issue I was facing: updating the jupyter extension or downgrading the system. But I did try with AML extension enabled as well as disabled everything worked fine. please tell me if you need more clarification.

**Comment by DonJayamanne** [comment]
@ameyb22 
Please could you install the latest vscode insiders and the pre-release version os the Jupyter and Python extension and let me know if this still persists.
Optionally you can wait for the next stable build that goes out some time today or later this week.
