### ISSUE TITLE
Overlapping cells when clearing long notebook after scrolling

### ISSUE THREAD

**Issue by 2-5** [microsoft/vscode-jupyter#12872]
## Environment data

-   VS Code version: 1.75.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.1.2010391206
-   Python Extension version (available under the Extensions sidebar): v2023.2.0
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.10.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Actual behaviour

Bad rendering with overlapping cells after clear

## Steps to reproduce:

1. Create new notebook
2. First cell:
```python
import pandas as pd
```
5. Second cell:
```python
#
#
#
#
#
#
#
#
pd.DataFrame(range(20))
```
6. Copy/paste second cell 6 times, so that it's longer than the screen
7. Run notebook
8. Scroll to notebook end
9. Select last cell
10. Scroll the notebook a bit up
11. Press `Clear All Outputs` button
12. You'll see something like in the screenshots below. It might take a few tries, it doesn't always happen. Try varying actions in steps 8-10.

## Screenshot 1

![2023-02-19_223147](https://user-images.githubusercontent.com/3753822/219973886-57cc18c4-bfba-452d-b1cb-8bb4b77492e0.png)

## Screenshot 2

![2023-02-19_222846](https://user-images.githubusercontent.com/3753822/219973902-869108aa-7415-4220-8e67-9a0d766db058.png)

## Screenshot 3, with customized notebook settings (no cell status bar, ...)

![2023-02-19_222240](https://user-images.githubusercontent.com/3753822/219973905-f0046a37-489b-46ed-b4f9-24a75528ee3a.png)

**Comment by rebornix** [comment]
This issue is likely fixed in latest Insiders and upcoming Stable release. Let's check once 1.76 is out.

**Comment by 2-5** [comment]
Still happens in 1.76.2

**Comment by hbsmith** [comment]
I've been having this problem for a few versions of vscode--since at least October 2022 (see issue I made here https://github.com/microsoft/vscode/issues/165273, whose behavior is related).

I tried disabling every extension not authored by Microsoft/Github/Julia and nothing has been able to resolve it.

Would be great if this was high priority--it really really slows down my workflow and has made me consider quitting Jupyter for VSCode entirely.

**Comment by ShuhongChen** [comment]
> Would be great if this was high priority--it really really slows down my workflow and has made me consider quitting Jupyter for VSCode entirely.

+1 on this, still happening on my 1.78.0, this bug effectively makes ipynb unusable for me in vscode

**Comment by almeidaxan** [comment]
+1

**Comment by royourboat** [comment]
+1, on 1.79.2

**Comment by royourboat** [comment]
Does anyone have tips of how to re-render the cells correctly? I move the width of the explorer or split from split-editor.

**Comment by hbsmith** [comment]
@royourboat If i scroll again, but this time slowly, they get rerendered correctly. But I would love a solution that isn't as finicky as this. Or even better, I would love if this bug ever got any attention since it makes vscode jupyter borderline unusable.

**Comment by DonJayamanne** [comment]
Are you still running into this issue?
We have made a few improvements in the past few months in this area and its possible this has been resolved?
