### ISSUE TITLE
VS Code Insiders Jupyter extension cannot open Jupyter Notebooks after 1.56 update

### ISSUE THREAD

**Issue by Khain1981** [microsoft/vscode-jupyter#5581]
## Environment data

-   VS Code version: Insiders 1.56
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.755784270
-   Python Extension version (available under the Extensions sidebar): v2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Enterprise version 10.0.18363
-   Python and/or Anaconda version: Python 3.7.10 conda 4.10.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local and Remote

## Expected behaviour

Jupyter notebooks are opened with no issues 

## Actual behaviour

Error Message:
Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed or enabled.

Error Message from Jupyter extension:
Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open VS Code Insiders
2. Open any Jupyter Notebook

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'NativeNotebookEditor'
Error 2021-04-21 09:55:19: extension activation failed [TypeError: this.notebook.onDidChangeActiveNotebookKernel is not a function
	at new T (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:49:656347)
	at Object.t.resolveInstance (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239967)
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239172
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239737)
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239172
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:238120
	at Array.map (<anonymous>)
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:238092
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239737)
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239172
	at Object.t.resolve (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239435)
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:230532
	at e._get (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:230298)
	at e.get (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:229010)
	at a.get (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:49:819305)
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:273220
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:32:773548
	at async t.activate (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:32:773235)
	at async Promise.all (index 0)]
Error 2021-04-21 09:55:19: Failed to active the Jupyter Extension [TypeError: this.notebook.onDidChangeActiveNotebookKernel is not a function
	at new T (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:49:656347)
	at Object.t.resolveInstance (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239967)
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239172
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239737)
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239172
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:238120
	at Array.map (<anonymous>)
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:238092
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239737)
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239172
	at Object.t.resolve (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:239435)
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:230532
	at e._get (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:230298)
	at e.get (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:229010)
	at a.get (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:49:819305)
	at c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:47:273220
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:32:773548
	at async t.activate (c:\Users\ejseglo\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.755784270\out\client\extension.js:32:773235)
	at async Promise.all (index 0)]
Info 2021-04-21 09:55:19: Found existing keyfile at c:\Users\ejseglo\AppData\Roaming\Code - Insiders\User\globalStorage\ms-toolsai.jupyter\nbsecret

```
</p>
</details>

**Comment by giuseppefilitto** [comment]
I have the same trouble

**Comment by Khain1981** [comment]
The problem remains with Jupyter extension v2021.6.770087802 ... still same output results

**Comment by eduardopaul** [comment]
Last time something like this happened, we were able to download an older version from a link like https://vscode-update.azurewebsites.net/1.55.0-insider/darwin/insider, but it's returning an error now. Is there another way we can do it now?

**Comment by Syndorik** [comment]
Do you know if there's a way to return to last night vscode insiders version?

**Comment by Khain1981** [comment]
It is possible to downgrade Jupyter extension from the arrow close to uninstall option ... but it doesn't matter ... I already did and it is still failing ... I think it is an issue with CS Code Insiders 1.56


![image](https://user-images.githubusercontent.com/10184456/115560683-bb934e80-a2ac-11eb-81a8-a9152b3e2d21.png)

**Comment by giuseppefilitto** [comment]
> It is possible to downgrade Jupyter extension from the arrow close to uninstall option ... but it doesn't matter ... I already did and it is still failing ... I think it is an issue with CS Code Insiders 1.56
> 
> ![image](https://user-images.githubusercontent.com/10184456/115560683-bb934e80-a2ac-11eb-81a8-a9152b3e2d21.png)

Exactly, I tried also to uninstall/downgrade the python extension but nothing change so there must be something wrong with VS-Code Insiders 1.56

**Comment by Syndorik** [comment]
Oh yes, I did not mean installing another version of jupyter extension, I already tried this without results. I was thinking downgrading vscode insiders to last night's build, cause it seems that today's build broke some stuffs

**Comment by IanMatthewHuff** [comment]
Hey everyone. Sorry there was a breaking change in VS Code insiders that we need to update to. Change incoming this morning.

**Comment by deepan-py** [comment]
![image](https://user-images.githubusercontent.com/60477808/115567660-1fcc0780-a2d9-11eb-9107-9cb2f7df0dd7.png)
when looking into settings.py I found this error recently I think it's regarding the new update

**Comment by IanMatthewHuff** [comment]
Yeah, the recent update made some big changes with how kernels are located and loaded with VS Code Native notebooks. When we push our update this morning there might be some issues with automatic kernel selection and the kernels listed in the selection dropdown. Widget support will probably also be broken for a little bit. We'll get it fixed up as quick as we can.

**Comment by IanMatthewHuff** [comment]
I just pushed a new version. The last three digits of the extension should end with 982 to know that you got the most recent version (it can sometimes take a bit longer to show up on the Extension tab). Coming in a bit hot, so we might see some issues here (and widgets will not be working for a bit) just create a new issue to report them, or you can bump on this thread.

**Comment by jaymegordo** [comment]
@IanMatthewHuff can confirm I'm back up and running on all the latest versions, thx for the super fast fix!!!

**Comment by Khain1981** [comment]
Issue fixed ... the World is saved again but ... for how long?! XD ... Thanks a million!

**Comment by giuseppefilitto** [comment]
@IanMatthewHuff Thank you man! I confirm everything, now it works fine but widgets still doesn't, should we create a new issue?

**Comment by IanMatthewHuff** [comment]
Right now there are a lot of changes coming in on the Notebook API from the VS Code side. But this is to be expected as it's in proposedAPI state, meaning that they are still iterating hard on getting the API correct. Once this API is upgraded to stable we should see less changes and a smoother experience with this. For now there still will be some hiccups from time to time on insiders in particular.

@giuseppefilitto I actually just opened up an issue as this was a known problem. You can track #5586 if you want to follow this fix. Shouldn't take too long.

**Comment by giuseppefilitto** [comment]
@IanMatthewHuff Thank you so much, you saved my day!
I would also thank and mention @Khain1981 for opening this issue on the morning

**Comment by eduardopaul** [comment]
Thanks a lot for the quick fix. But for posterity's sake, is there a way to install an old VSCode Insiders' version in case this ever happens again?

**Comment by IanMatthewHuff** [comment]
@eduardopaul I don't actually know of a way to roll back insiders like that aside from actually building it from source and syncing to a specific commit. I'll loop with the VS Code core team though to see if some way to do this does exist.

**Comment by greazer** [comment]
Please see https://github.com/microsoft/vscode/issues/46089 for how to download older versions of Insiders.

**Comment by eduardopaul** [comment]
@greazer Thanks for the info, but I'm getting a "Cannot GET /api/releases/insider" type error when trying those links. Is it just me or is there something going on?
