### ISSUE TITLE
Some Issues since latest update of IPython

### ISSUE THREAD

**Issue by Ov-ille** [microsoft/vscode-jupyter#7149]
## Environment data

-   VS Code version:  1.59.0
-   Jupyter Extension version (available under the Extensions sidebar): v.2021.8.1195043623
-   Python Extension version (available under the Extensions sidebar): v.2021.8.1105858891
-   OS (Windows | Mac | Linux distro) and version: WIn 10
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

Previously the following things were working:
- When running the IPython environment in VS Code, it would automatically pick the set virtual environment for the folder of the workspace. 
- When executing lines of code in the IPython console, VS Code would indicate when it was still running code (little not "Executing" and a spinning circle on the bottom left 

## Actual behaviour
- VS Code still states the correct venv on the bottom left, but when starting IPython it just picks the "normal" Python version and one has to manually change it in the top right corner
- There is no directly visible indicator if IPython is still busy or already finished executing code. One has to manually expand the cell to see if there is the little green tick underneath

## Steps to reproduce:

- run IPython for different venv's 
- run lines of code and try to see when it is done

**Comment by greazer** [comment]
Thanks for the feedback, @Ov-ille. The second issue you mentioned has been fixed in the latest VS Code insiders build. The picking of the wrong Python is something we need to investigate further. It should be choosing the same environment as is set in the status bar.

**Comment by Ov-ille** [comment]
@greazer Thank you for looking into this. It's actually causing alot of problems at the moment. Sometimes it takes many, many attempts of restarting the jupyter kernel until the correct venv is actually started. Even when it states the correct venv in the upper right corner, it's sometimes still not using the right one (I can tell when importing a venv specific module)

Also, not all existing venv's appear when clicking on the selected kernel in the top right corner of the interactive window and I just can't get them to work.

Those were never issues before the last update!

**Comment by joyceerhl** [comment]
@Ov-ille We fixed an issue with the wrong interpreter being picked https://github.com/microsoft/vscode-jupyter/commit/69ae8c3adae683d009d2f81c9ae06c85e6bbc029 We are publishing a new Stable version of the Jupyter extension tomorrow or Thursday which should resolve these issues, and the fix is also available in Insiders. Please let us know if the issue persists in Insiders or the upcoming Stable build. Apologies for the inconvenience.
