### ISSUE TITLE
Notebook debugger could not load source

### ISSUE THREAD

**Issue by jingw222** [microsoft/vscode-jupyter#7555]
## Environment data

-   Language Server version: 2021.9.1
-   OS and version: both Windows 10 and MacOS 14
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5

## Expected behaviour

Debugger step into inner function/method body

## Actual behaviour
When I click `step into` it throws me a tmp py file which says 
```
Could not load source XXX: source unavailable.
```
![image](https://user-images.githubusercontent.com/5494367/133536876-519e7704-efaf-4e66-b0f0-976c1df6bd61.png)
## Logs

```
Not relevant 
```

## Code Snippet / Additional information

```python
# Screenshot above
```

**Comment by jingw222** [comment]
Anybody looking into the cause of the issue? I've been wanting to migrate all my notebook workflow into VSCode since last couple of weeks. But my latest experiences of it hold me back, as you might tell from the various issues I submitted lately, and I have a few other frustrations that I encountered with VSCode but not JupyterLab. Maybe it's still in experimenting phase and not prime for daily usage at the moment

**Comment by DonJayamanne** [comment]
Assigning to @DavidKutu 
@roblourens Not sure if we've addressed this scneario

**Comment by DavidKutu** [comment]
Thanks for the issue @jingw222. The code snippet is very helpful.

**Comment by roblourens** [comment]
Note that the debugging feature specifically is considered experimental. You either set the experimental setting or are using Insiders (where we just enabled this without the experimental setting to get more coverage).

**Comment by DavidKutu** [comment]
@jingw222, this will be fixed on tomorrow's insiders and on our next release.

**Comment by jingw222** [comment]
Hey @DavidKutu, thanks for your awesome work, but it's interesting I'm still getting the same result as before though 
```
Version: 1.61.0-insider (user setup)
Commit: 1b9403cd461c9c975bcb9e48d84ba9e4ea86559e
Date: 2021-09-21T09:01:24.526Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17134
```

**Comment by roblourens** [comment]
This works for me. Could you try this?

- Set `"jupyter.logging.level": "verbose"`
- Try your case again
- Share the log from the `Jupyter` output channel

**Comment by jingw222** [comment]
Upgraded the Python extension to the latest in dev channel, it's working as expected now. I'll let you know if anything pops up while testing more cases.

**Comment by roblourens** [comment]
Please do, thanks for trying it
