### ISSUE TITLE
cannot find kernel in interactive window again

### ISSUE THREAD

**Issue by zesluo** [microsoft/vscode-jupyter#7561]
## Environment data

Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

## Actual behaviour
 The kernel disappeared again by updating to the latest ms-python
![image](https://user-images.githubusercontent.com/46309533/133640587-255a3d5d-de61-42b4-9488-c56da6ead9e6.png)

When using "`Python: Select Interpreter", it shows up
[jupyteroutout.txt](https://github.com/microsoft/vscode-jupyter/files/7179129/jupyteroutout.txt)

![image](https://user-images.githubusercontent.com/46309533/133641200-790b1674-d733-4a3e-adab-3f26dade3cb0.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
* Please could you provide the version of the Jupyter & Python extension

> When using "`Python: Select Interpreter", it shows up

Which one are you referring to, please could you be specific.
Looking at the screenshots the item `~\msvscode.....\hdinsight\scripts\python.exe` is showing up in both places.

* Also looking at the screenshots, looks like you have a pending update on the python extension. Please could you update the python extenison & try again.

* Finally, based on the logs, none of the python interprters have been discovered.
This is a problem that was recently fixed in the python extension. Please update and try again.
Once done, please provide the logs.

**Comment by zesluo** [comment]
Thanks for your reply, Don.
1."Please could you provide the version of the Jupyter & Python extension"
Jupyter: v2021.8.2041215044
python ext:v2021.9.1230869389
2."Which one are you referring to, please could you be specific.
Looking at the screenshots the item ~\msvscode.....\hdinsight\scripts\python.exe is showing up in both places."
The left bottom place.
3.Updated but still cannot see the expected kernels:
[jpteroutput0921.txt](https://github.com/microsoft/vscode-jupyter/files/7197352/jpteroutput0921.txt)

**Comment by DonJayamanne** [comment]
Can you try the following:
* Open your user settings.json file and add the following settings
```jsonc
"python.insidersChannel": "off",
"python.experiments.enabled": true,
"python.experiments.optOutFrom": ["All"],
"python.logging.level": "debug"
```

* Reload VS Code
* Test again
* Provide the logs from the `Python` output chanell & `Jupyte` channel.

> .Updated but still cannot see the expected kernels:

What is missing please could you provide the exact name & path that you expect to see.
I want to know exactly what to look for, what string, what path or kernel spec.

**Comment by zesluo** [comment]
Hello Don, here are the logs:
[jupyter0927.txt](https://github.com/microsoft/vscode-jupyter/files/7237720/jupyter0927.txt
[pythonlog0927.txt](https://github.com/microsoft/vscode-jupyter/files/7237721/pythonlog0927.txt)
)
![image](https://user-images.githubusercontent.com/46309533/134944290-4c67d218-c842-45cf-9c43-1d8424b2080a.png)

still cannot see the expected kernel.
In fact, I want to see kernels like this:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/46309533/134945915-41f27c67-5770-4dae-90e2-e7139ffae0cb.png)
Thanks!

**Comment by DonJayamanne** [comment]
**Please can you try this**
Looking at your logs you don't seem to have disabled the experiments in Python extension.

Open your user settings.json file and add the following settings
"python.insidersChannel": "off",
"python.experiments.enabled": true,
"python.experiments.optOutFrom": ["All"],
"python.logging.level": "debug"
"jupyter.logging.level": "debug"

Please save the changes, reload VS Code and provide both the logs again.
